---
- name: Meu primeiro playbook
  hosts: local #Grupo do invent치rio (maquina) onde vai executar
  tasks:  # Lista de tarefas a executar
    - name: Criar arquivo de teste
      file: # m칩dulo
        path: /tmp/playbook-teste.txt
        state: touch

    - name: Adicionar conteudo ao arquivo
      copy: # m칩dulo
        content: "Arquivo criado pelo playbook Ansible\n"
        dest: /tmp/playbook-teste.txt

    - name: Mostrar mensagem
      debug: # m칩dulo
        msg: "Playbook executado com sucesso!"