---
- name: Instalar Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copiar configuracao do Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reiniciar Nginx

- name: Copiar pagina inicial
  template:
    src: index.html.j2
    dest: "{{ document_root }}/index.html"

- name: Garantir que Nginx esta rodando
  service:
    name: nginx
    state: started
    enabled: yes